<link rel="stylesheet" href="{{ asset('assets/css/vendor/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/vendor/font-awesome.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/vendor/flaticon/flaticon.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/vendor/slick.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/vendor/slick-theme.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/vendor/jquery-ui.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/vendor/sal.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/vendor/magnific-popup.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/vendor/base.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/style.min.css') }}">